# Generated by Django 4.1.1 on 2022-09-09 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prowler_post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='name',
            field=models.CharField(default='user', max_length=20),
        ),
    ]
